name: My first workflow

on: [push, workflow_dispatch]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: List all files
        run: ls -a
      - name: Print working directory
        run: pwd 

  second-jon:
    runs-on: ubuntu-latest
    steps:
        - name: Clone repository
          run: git clone https://github.com/saifraja07/Custom-CICD-Server.git
        - name: checkout to cloned repository
          run: cd Custom-CICD-Server
        - name: Install dependencies
          run: npm ci
        - name: start server
          run: node app.js
        - name: Setup tmate session
          uses: mxschmitt/action-tmate@v3
