name: My first workflow

on: [push, workflow_dispatch]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: List all files
        run: ls -a
      - name: Print working directory
        run: pwd
      - name: nginx version
        run: nginx -v
      - name: ngrok version
        run: ngrok -v

  second-jon:
    runs-on: ubuntu-latest
    steps:
        - name: Setup tmate session
          uses: mxschmitt/action-tmate@v3
